---
title: "Cox regression OS, continuous values"
output:
  pdf_document: default
  html_document: default
---

```{r load libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl)
library(survival)
library(knitr)
```

```{r read the data, message=FALSE, warning=FALSE}
df <- read_excel ("data/BOMI2_BOMI1_data_Continuous_Final.xlsx")
```

```{r, message=FALSE, warning=FALSE}
df <- drop_na(df)
var_names <- colnames(df)
M <- nrow(as.matrix(var_names))
p <- list()
hr <- list()

k <- 1
for (i in 2:M) {
  cmodel <- coxph(Surv(OS_Time, OS_Status) ~ df[[i]], data = df)
  s <- summary(cmodel)
  p[k]  <- s$logtest["pvalue"]
  hr[k] <- s$coefficients[2]
  rm(cmodel, s)
  k <- k + 1 
}


res <- tibble(variables = var_names[2:end(var_names)],p = as.numeric(p),hr = as.numeric(hr)) %>% 
  drop_na() %>% 
  filter( variables != "ID", variables != "OS_Status", variables != "OS_Time")

res <- res %>% mutate(p_cor = p.adjust(p, method = "fdr"))

write_csv(res, "res.csv")

kable(res)

```



```{r fig.height=25, fig.width=10}

res %>% ggplot(aes(x = reorder(variables, -p))) +
  geom_col(aes(y = log10(p_cor), fill = hr > 1)) +
  #geom_hline(yintercept = log10(0.05 / nrow(res)) ) + 
  coord_flip()
  
```

